version: '3.3'

services:
  doc_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH}:/app/data
      - ${OUTPUT_DIR}:/app/output

    ports:
      - '8080:8080'
    container_name: doc_app
    networks:
      - app

  tf_serving:
    ports:
      - '8501:8501' 
    container_name: persi_doc
    environment:
      - MODEL_NAME=saved_model
    image: tensorflow/serving
    volumes:
      - type: bind
        source: ./model/
        target: /models/saved_model/1
    networks:
      - app

networks:
  app:
    driver: bridge
